language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r ij_testProject *
  - mkdir -p deploy
  - mv ij_testProject.zip deploy/ij_testProject.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo setting에 설정된 값
    bucket: ksh-springboot-build #s3버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY #Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo setting에 설정된 값
    bucket: ksh-springboot-build #s3버킷
    key: ij_testProject.zip
    bundle_type: zip
    application: springboot2-webservice # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: springboot2-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - tkdguq9369@naver.com
